### PR TITLE
exclude_file parameter fix

### PR DESCRIPTION
**Pull request by popstas**
Was include_file

### CODE REVIEW

**Comment by sebalix** [comment]
@popstas Whoops, thank you!

**Comment by popstas** [comment]
Are you understand why travis build was failed?

**Comment by sebalix** [comment]
Yes, it is failing on older Ansible version (< 1.8, but it works fine on 1.8). I plan to remove support for these versions anyway + add tests for Ansible 2.X.

**Comment by sebalix** [comment]
@popstas Here is the support for Ansible 2.X : https://github.com/osiell/ansible-rsnapshot-master/pull/5

**Pull request merged**
